# Generated by Django 5.1 on 2024-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
